const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

/**
 * Generates an ownership certificate PDF for an NFT.
 * @param {Object} data - The certificate data.
 * @param {string} data.ownerName - Name of the new owner.
 * @param {string} data.sellerName - Name of the seller or creator.
 * @param {string} data.title - Title of the NFT/Collectible.
 * @param {number} data.copyNumber - The specific copy number sold (1 if auction).
 * @param {number} data.totalCopies - The total copies available (1 if auction).
 * @param {Date} data.date - The date of acquisition.
 * @returns {Promise<Buffer>} - A promise that resolves to the PDF buffer.
 */
const generateCertificate = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const { ownerName, sellerName, title, copyNumber, totalCopies, date } = data;
      
      const doc = new PDFDocument({ margin: 50, size: 'A4', layout: 'landscape' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Background and Border
      doc.rect(20, 20, 800, 555).lineWidth(10).strokeColor('#2c3e50').stroke();
      doc.rect(30, 30, 780, 535).lineWidth(2).strokeColor('#34495e').stroke();

      const logoPath = path.join(__dirname, '../../frontend/public/knqlogo-removebg-preview (1).png');
      
      // Watermark
      if (fs.existsSync(logoPath)) {
        doc.save();
        doc.opacity(0.06); // Very light opacity for watermark
        // A4 Landscape width is ~842, height is ~595. Center a 500x500 image.
        doc.image(logoPath, 171, 47, { width: 500 });
        doc.restore();
      }

      // Add Logo at the top center
      if (fs.existsSync(logoPath)) {
        doc.image(logoPath, 371, 35, { width: 100 });
        doc.moveDown(5.5);
      } else {
        doc.moveDown(1);
      }

      // Title
      doc.font('Helvetica-Bold')
         .fontSize(36)
         .fillColor('#2c3e50')
         .text('Certificate of Digital OwnerShip', { align: 'center' });

      doc.moveDown(0.5);

      // Body text
      doc.font('Helvetica')
         .fontSize(16)
         .fillColor('#333333')
         .text('This certifies that', { align: 'center' });

      doc.moveDown(0.3);

      doc.font('Helvetica-Bold')
         .fontSize(26)
         .fillColor('#e74c3c')
         .text(ownerName || 'Unknown User', { align: 'center' });

      doc.moveDown(0.5);

      doc.font('Helvetica')
         .fontSize(16)
         .fillColor('#333333')
         .text('is the official owner of the digital collectible:', { align: 'center' });

      doc.moveDown(0.3);

      doc.font('Helvetica-Bold')
         .fontSize(22)
         .fillColor('#2980b9')
         .text(title || 'Untitled NFT', { align: 'center' });

      doc.moveDown(0.5);

      if (sellerName) {
         doc.font('Helvetica')
            .fontSize(14)
            .fillColor('#333333')
            .text('Acquired from Seller / Creator:', { align: 'center' });
         doc.moveDown(0.2);
         doc.font('Helvetica-Bold')
            .fontSize(18)
            .fillColor('#8e44ad')
            .text(sellerName, { align: 'center' });
         doc.moveDown(0.5);
      }

      // Copy Information
      doc.font('Helvetica-Oblique')
         .fontSize(14)
         .fillColor('#7f8c8d')
         .text(`Copy: ${copyNumber} out of ${totalCopies} copies`, { align: 'center' });

      doc.moveDown(0.5);

      // Date
      const formattedDate = date ? new Date(date).toLocaleDateString() : new Date().toLocaleDateString();
      doc.font('Helvetica')
         .fontSize(14)
         .fillColor('#2c3e50')
         .text(`Date of Acquisition: ${formattedDate}`, { align: 'center' });

      // Footer
      doc.fontSize(12)
         .fillColor('#95a5a6')
         .text('Generated by KnQ Digital Marketplace', 50, 520, { align: 'center', width: 740 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateCertificate };
